[rewrite] for Nutrimenu API
epfl-si/wp-plugin-epfl-restauration pull request #1
Opened 2021-11-09 13:10 UTC by WolffJeremy

Hello,

Voici la nouvelle version du nouveau système de gestion des menus de restauration, appelant l'API de nutriMenu. 
L'affichage des menus et des horaires se fait directement dans le plugin. La réponse de l'API est mise en cache pendant 10 minutes. Le filtrage des menus est fait avec du code JavaScript.
Nous avons une date de mise en production pour le jeudi 18 novembre.

Bonne journée et meilleures salutations.

Jérémy Wolff

2021-11-15 15:02 UTC, domq requested changes
Veuillez changer le nom de la pull request en quelque chose du genre :

[rewrite] for Nutrimenu API

2021-11-15 15:02 UTC, domq commented on .gitignore
> +/.idea
Merci de ne pas ajouter de .gitignore pour des fichiers qui ne sont pas utilisés par tous les développeurs. 💡 On peut obtenir le même effet, sans interférer avec les collègues, en éditant le fichier `.git/info/exclude`.

2021-11-15 15:02 UTC, domq commented on css/style.css
> +.ms-choice:hover{
Ces changements de style s'appliquent, en l'état, à tout le site dès lors que le plug-in est actif. Veuillez les garder avec un filtre CSS plus spécifique (qui porte par exemple sur un ID ou classe ancêtre qu'on ne trouve que dans le plug-in restauration)

2021-11-15 15:02 UTC, domq commented on css/style.css
> +    display:none !important;
Merci de ne pas utiliser `!important` dans les CSS.

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +define("REMOTE_SERVER_TIMEOUT", 10);  // time to wait until we consider the remote server out of the game
Pour éviter les conflits de noms, ces defines doivent être préfixés par quelque chose qui les rend unique. Par exemple : 

```
define("EPFL_RESTAURATION_REMOTE_SERVER_TIMEOUT", 10);
```

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +    global $ini_array_sections;
Veuillez éviter les variables globales.

On peut remplacer celle-ci par une fonction en lieu et place de la ligne 17, qui (par optimisation) utilise une variable statique (https://www.php.net/manual/en/language.variables.scope.php#language.variables.scope.static) pour ne pas charger une seconde fois le fichier de configuration s'il a déjà été chargé.

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +    $images_path = get_option("home") . "/wp-content/plugins/epfl-restauration/images/";
Cette variable n'est pas utilisée

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +    $vars = parse_url( $params, $component = -1 );
Cette variable n'est pas utilisée; la seconde expression ne fait probablement pas ce que vous croyez qu'elle fait

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +        $selected_resto_id = $params_array['resto_id'];
Cette entrée de l'utilisateur n'est pas contrôlée. Un attaquant pourrait se servir de ce fait pour attaquer le serveur d'API, ou pour mettre en place une attaque dite XSS (Cross-Site Scripting)

Veuillez contrôler, par exemple à l'aide d'une expression régulière, que $selected_resto_id ne contient que des caractères tirés d'une liste limitative. Plus d'informations à ce sujet : https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +        $selected_date = filter_input(INPUT_GET, 'date', FILTER_SANITIZE_STRING);
Là c'est bien par contre ☺

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +    if(get_locale() == "en_US" || get_locale() == "en_GB") $params_array['lang'] = "en";
Veuillez éviter les formes “if” avec la conséquence sur la même ligne.

2021-11-15 15:02 UTC, domq commented on css/style.css
> +/*span.price {*/
Veuillez supprimer tout le code mort.

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +        /*"ssl"=>array(
Veuillez supprimer ce code mort.

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +//    if (false === ( $menus_file = get_transient( $cache_key ) ) ) {
Veuillez supprimer ce code mort, ou le rendre conditionnel à un paramètre du fichier de configuration ou à une option en base.

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +    $cache_key = LOCAL_CACHE_NAME . md5(serialize($remote_url_api));
La fonctionnalité de cache couvre l'entier du processus, et le cas «cache plein» devrait donc être contrôlé plus tôt (avant de construire $cred). Veuillez refactorer pour rendre ce fait clair. Par exemple, une fonction `get_menu(...)` pourrait appeler une fonction `get_menu_nocache(...)` en cas de cache vide.

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +    // Decodes JSON's file
Les commentaires expliquent pourquoi, non pas comment. Ici, tout lecteur compétent soit sait ce que fait la fonction `json_decode()`, soit peut le découvrir en quelques instants. Veuillez reformuler ou supprimer ce commentaire.

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +    // Sort Restaurant alpha
Même remarque sur le commentaire : la fonction de la ligne suivante est claire pour un lecteur compétent.

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +    // Test array for error
Veuillez supprimer ce code mort.

2021-11-15 15:02 UTC, domq commented on schedule.php
> +<table class="table tablesaw tablesaw-stack <?php if(!empty($selected_resto_id)) echo 'single-schedule' ?>">
Si ce fichier n'a pas vocation à être un point d'entrée direct (autrement dit il ne sert qu'à être inclus depuis 
`epfl-restauration.php`), veuillez le renommer en `schedule.inc` pour éviter un canal d'attaque consistant à l'appeler directement. (Et par ailleurs, 👍 pour avoir séparé la présentation du code de configuration et d'interrogation du serveur)

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +// Web page content traduction
En anglais, «traduction» se dit “translation”

2021-11-15 15:02 UTC, domq commented on epfl-restauration.php
> +// Error function
Ce commentaire explique insuffisamment à quoi sert cette fonction. Suggestion de remplacement :

```
// Render an error message to be displayed in lieu of the menu in case of an error
```

2021-11-15 15:02 UTC, domq commented on js/script.js
> +    // const nutriScoresArray = [
Veuillez supprimer ce code mort.

2021-11-15 15:02 UTC, domq commented on js/script.js
> +    console.log("NutriScore sélectionné : " + nutriScoresArray[currentNutriScore].val + " text " + nutriScoresArray[currentNutriScore].txt);
Veuillez supprimer les aides de débogage telles que celle-ci.

2021-11-15 15:02 UTC, domq commented on js/script.js
> +        // console.log(menuLine);
À supprimer

2021-11-15 15:02 UTC, domq commented on js/script.js
> +                // console.log('Selected restaurant : ');
Code mort, à supprimer

2021-11-15 15:02 UTC, domq commented on js/script.js
> +                    console.log("Menu line is restaurant : " + $(this).val());
Veuillez supprimer cette aide au débogage

2021-11-15 15:02 UTC, domq commented on js/script.js
> +                // console.log('Selected menu : ');
À supprimer

2021-11-15 15:02 UTC, domq commented on js/script.js
> +                    console.log("Menu line is type : " + $(this).val());
À supprimer

2021-11-15 15:02 UTC, domq commented on js/script.js
> +        // console.log('NS du menu (auto) : ' + nsValue + ', NS sélectionné -> ' + nutriScoresArray[currentNutriScore].txt + ' : ' + nutriScoresArray[currentNutriScore].val);
À supprimer

2021-11-15 15:02 UTC, domq commented on js/script.js
> +    console.log('Tag to be removed : ' + iD);
Supprimer les console.log

2021-11-15 15:02 UTC, domq commented on js/script.js
> +    // console.log('Selected restaurants tags (after removing the tag) : ');
Code mort à supprimer

2021-11-15 15:02 UTC, domq commented on js/script.js
> +    // Actualise the selected restaurants options after removing the restaurant tag
En anglais, «actualiser» se dit “update”

2021-11-15 15:02 UTC, domq commented on js/script.js
> +    // MENUS TYPES
En anglais, le complément du nom ne s'accorde pas (“menu types”)

2021-11-15 15:02 UTC, domq commented on js/script.js
> +    // console.log('Selected menus types tags (before removing the tag) : ');
À supprimer

2021-11-15 15:02 UTC, domq commented on js/script.js
> +    // console.log('Selected menus types tags (after removing the tag) : ');
Code mort à supprimer

2021-11-15 15:02 UTC, domq commented on js/script.js
> +});
Veuillez vous assurer que chaque fichier finit par un retour à la ligne.

2021-11-15 15:02 UTC, domq commented on menus.ini
> +error_configuration = "missing configuration"
Veuillez vous assurer que chaque fichier finit par un retour à la ligne.

2021-11-15 15:02 UTC, domq commented on readme.md
> +**epfl-restauration** is a WordPress plugin used to display on the  web site the EPFL's daily offers and opening hours of all the restaurants on the campus. This plugin calls an API from nutriMenu wh
Remplacer “app” (en fin de ligne) par “plugin”

2021-11-15 15:31 UTC, jdelasoie reviewed
Bonjour,
Comme demandé, voici mon review.

A+
Julien

2021-11-15 15:31 UTC, jdelasoie commented on .gitignore
> +/.idea
Je suis partisant que les gitignore d'IDE ne devraient  pas trouver leur place dans le projet, mais dans la configuration système de chaque utilisateur. Par exemple : `git config --global core.excludesfile ~/.gitignore`
```suggestion
```

2021-11-15 15:31 UTC, jdelasoie commented on epfl-restauration.php
> +    $images_path = get_option("home") . "/wp-content/plugins/epfl-restauration/images/";
je me sentirais plus serein avec
```suggestion
    $images_path = plugin_dir_url(__FILE__) . "images/";
```

2021-11-15 15:31 UTC, jdelasoie commented on epfl-restauration.php
> +    if(get_locale() == "en_US" || get_locale() == "en_GB") $params_array['lang'] = "en";
Je ne suis pas certain que cela donnera le résultat escompté, je crois que get_locale retourne la valeur "locale" du serveur, pas de la page. Personnellement nous utilisons cette démarche :
https://github.com/epfl-si/wp-gutenberg-epfl/blob/c48a884895bda9e53fdefa98bef88a3c4228f317/frontend/lib/language.php. A étudier

2021-11-15 15:31 UTC, jdelasoie commented on readme.md
> +# epfl-restauration
Merci pour ce joli readme :+1:

2021-11-15 15:31 UTC, jdelasoie commented on js/script.js
> +    // const nutriScoresArray = [
Est-ce encore utile ?

2021-11-16 09:15 UTC, WolffJeremy commented on css/style.css
> +    display:none !important;
OK, c'est corrigé.

2021-11-16 09:55 UTC, WolffJeremy commented on readme.md
> +# epfl-restauration
Merci!

2021-11-16 09:55 UTC, WolffJeremy commented on js/script.js
> +    // const nutriScoresArray = [
Non, ce n'est plus utile... --> supprimé!

2021-11-16 14:00 UTC, WolffJeremy commented on css/style.css
> +    display:none !important;
Je n'ai pas trouvé de moyen de faire sans "!important".
Le code a par contre été adapté comme suit (classes select-resto et select-menu) afin qu'il ne s'applique seulement au plugin epfl-restauration:

/* Hide [Select all] option (checkboxes) */
.select-resto .ms-select-all, .select-menu .ms-select-all {
    display:none !important;
}

2021-11-16 16:16 UTC, domq approved these changes

2021-11-16 16:16 UTC, merged